import Header from './_components/header/header'
import Footer from './_components/footer/footer'
import './globals.css'
import Head from 'next/head'
import Prvider from './redux/provider/Prvider'
import { useRouter } from 'next/navigation'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ pathname, children }) {
  const isCataloguePage = pathname === '/catalogue'
  return (
    <html lang="en">
      <Head />
      <body>
        <Prvider>
        {isCataloguePage ? (
          <>
          <Header />
            {children}
          <Footer />
          </>
          ) : (
            <>
             <Header />
            {children}
            </>
          )}
        </Prvider>
      </body>
    </html>
  )
}
