import Header from './_components/header/header'
import Footer from './_components/footer/footer'
import './globals.css'
import Head from 'next/head'
import Prvider from './redux/provider/Prvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head />
      <body>
        <Prvider>
          <Header />
            {children}
          <Footer />
        </Prvider>
      </body>
    </html>
  )
}
